// (-- api-linter: core::0191::proto-package=disabled
//     aip.dev/not-precedent: We need to do this because reasons. --)
// (-- api-linter: core::0136::request-message-name=disabled
//     aip.dev/not-precedent: It is a stream. --)
// (-- api-linter: core::0136::response-message-name=disabled
//     aip.dev/not-precedent: It is a stream. --)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: revent/v1/control.proto

package reventv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Control_OpenSession_FullMethodName = "/revent.v1.Control/OpenSession"
)

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Control provides bidirectional communication between clients and the server.
type ControlClient interface {
	// OpenSession opens a bidirectional stream between a client and the server.
	OpenSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientToServerMessage, ServerToClientMessage], error)
}

type controlClient struct {
	cc grpc.ClientConnInterface
}

func NewControlClient(cc grpc.ClientConnInterface) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) OpenSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientToServerMessage, ServerToClientMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[0], Control_OpenSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientToServerMessage, ServerToClientMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_OpenSessionClient = grpc.BidiStreamingClient[ClientToServerMessage, ServerToClientMessage]

// ControlServer is the server API for Control service.
// All implementations must embed UnimplementedControlServer
// for forward compatibility.
//
// *
// Control provides bidirectional communication between clients and the server.
type ControlServer interface {
	// OpenSession opens a bidirectional stream between a client and the server.
	OpenSession(grpc.BidiStreamingServer[ClientToServerMessage, ServerToClientMessage]) error
	mustEmbedUnimplementedControlServer()
}

// UnimplementedControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServer struct{}

func (UnimplementedControlServer) OpenSession(grpc.BidiStreamingServer[ClientToServerMessage, ServerToClientMessage]) error {
	return status.Error(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedControlServer) mustEmbedUnimplementedControlServer() {}
func (UnimplementedControlServer) testEmbeddedByValue()                 {}

// UnsafeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServer will
// result in compilation errors.
type UnsafeControlServer interface {
	mustEmbedUnimplementedControlServer()
}

func RegisterControlServer(s grpc.ServiceRegistrar, srv ControlServer) {
	// If the following call panics, it indicates UnimplementedControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Control_ServiceDesc, srv)
}

func _Control_OpenSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServer).OpenSession(&grpc.GenericServerStream[ClientToServerMessage, ServerToClientMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_OpenSessionServer = grpc.BidiStreamingServer[ClientToServerMessage, ServerToClientMessage]

// Control_ServiceDesc is the grpc.ServiceDesc for Control service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Control_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revent.v1.Control",
	HandlerType: (*ControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenSession",
			Handler:       _Control_OpenSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "revent/v1/control.proto",
}
