// (-- api-linter: core::0191::proto-package=disabled
//     aip.dev/not-precedent: We need to do this because reasons. --)
// (-- api-linter: core::0136::request-message-name=disabled
//     aip.dev/not-precedent: It is a stream. --)
// (-- api-linter: core::0136::response-message-name=disabled
//     aip.dev/not-precedent: It is a stream. --)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: revent/v1/control.proto

package reventv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// ClientToServerMessage contains messages sent from the client to the server over Connect.
type ClientToServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientToServerMessage_RegisterClient
	//	*ClientToServerMessage_QueryRequest
	//	*ClientToServerMessage_QueryResponse
	//	*ClientToServerMessage_RegisterSourceEvent
	//	*ClientToServerMessage_Heartbeat
	Payload       isClientToServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToServerMessage) Reset() {
	*x = ClientToServerMessage{}
	mi := &file_revent_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToServerMessage) ProtoMessage() {}

func (x *ClientToServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_revent_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToServerMessage.ProtoReflect.Descriptor instead.
func (*ClientToServerMessage) Descriptor() ([]byte, []int) {
	return file_revent_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *ClientToServerMessage) GetPayload() isClientToServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientToServerMessage) GetRegisterClient() *RegisterClient {
	if x != nil {
		if x, ok := x.Payload.(*ClientToServerMessage_RegisterClient); ok {
			return x.RegisterClient
		}
	}
	return nil
}

func (x *ClientToServerMessage) GetQueryRequest() *QueryRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientToServerMessage_QueryRequest); ok {
			return x.QueryRequest
		}
	}
	return nil
}

func (x *ClientToServerMessage) GetQueryResponse() *QueryResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientToServerMessage_QueryResponse); ok {
			return x.QueryResponse
		}
	}
	return nil
}

func (x *ClientToServerMessage) GetRegisterSourceEvent() *RegisterSourceEvent {
	if x != nil {
		if x, ok := x.Payload.(*ClientToServerMessage_RegisterSourceEvent); ok {
			return x.RegisterSourceEvent
		}
	}
	return nil
}

func (x *ClientToServerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ClientToServerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isClientToServerMessage_Payload interface {
	isClientToServerMessage_Payload()
}

type ClientToServerMessage_RegisterClient struct {
	// Registers a client with the server.
	RegisterClient *RegisterClient `protobuf:"bytes,1,opt,name=register_client,json=registerClient,proto3,oneof"`
}

type ClientToServerMessage_QueryRequest struct {
	// Submits a query request.
	QueryRequest *QueryRequest `protobuf:"bytes,2,opt,name=query_request,json=queryRequest,proto3,oneof"`
}

type ClientToServerMessage_QueryResponse struct {
	// Provides a query result in response to a QueryRequested message.
	QueryResponse *QueryResponse `protobuf:"bytes,3,opt,name=query_response,json=queryResponse,proto3,oneof"`
}

type ClientToServerMessage_RegisterSourceEvent struct {
	// Indicates that an event happened.
	RegisterSourceEvent *RegisterSourceEvent `protobuf:"bytes,4,opt,name=register_source_event,json=registerSourceEvent,proto3,oneof"`
}

type ClientToServerMessage_Heartbeat struct {
	// Indicates that the client is still connected.
	Heartbeat *Heartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

func (*ClientToServerMessage_RegisterClient) isClientToServerMessage_Payload() {}

func (*ClientToServerMessage_QueryRequest) isClientToServerMessage_Payload() {}

func (*ClientToServerMessage_QueryResponse) isClientToServerMessage_Payload() {}

func (*ClientToServerMessage_RegisterSourceEvent) isClientToServerMessage_Payload() {}

func (*ClientToServerMessage_Heartbeat) isClientToServerMessage_Payload() {}

// *
// RegisterClient registers a client and declares the queries it can handle.
type RegisterClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the client registering with the server.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Query IDs this client can handle.
	QueryHandlers []string `protobuf:"bytes,2,rep,name=query_handlers,json=queryHandlers,proto3" json:"query_handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClient) Reset() {
	*x = RegisterClient{}
	mi := &file_revent_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClient) ProtoMessage() {}

func (x *RegisterClient) ProtoReflect() protoreflect.Message {
	mi := &file_revent_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClient.ProtoReflect.Descriptor instead.
func (*RegisterClient) Descriptor() ([]byte, []int) {
	return file_revent_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterClient) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterClient) GetQueryHandlers() []string {
	if x != nil {
		return x.QueryHandlers
	}
	return nil
}

// *
// Heartbeat indicates liveness of the sender.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_revent_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_revent_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_revent_v1_control_proto_rawDescGZIP(), []int{2}
}

// *
// ServerToClientMessage contains messages sent from the server to the client over Connect.
type ServerToClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerToClientMessage_ClientRegistered
	//	*ServerToClientMessage_QueryRequested
	//	*ServerToClientMessage_QueryResponded
	//	*ServerToClientMessage_Heartbeat
	//	*ServerToClientMessage_ClientRegistrationError
	//	*ServerToClientMessage_QueryRequestedError
	//	*ServerToClientMessage_SourceEventRegistered
	//	*ServerToClientMessage_SourceEvent
	Payload       isServerToClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToClientMessage) Reset() {
	*x = ServerToClientMessage{}
	mi := &file_revent_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClientMessage) ProtoMessage() {}

func (x *ServerToClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_revent_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClientMessage.ProtoReflect.Descriptor instead.
func (*ServerToClientMessage) Descriptor() ([]byte, []int) {
	return file_revent_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ServerToClientMessage) GetPayload() isServerToClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerToClientMessage) GetClientRegistered() *ClientRegistered {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClientMessage_ClientRegistered); ok {
			return x.ClientRegistered
		}
	}
	return nil
}

func (x *ServerToClientMessage) GetQueryRequested() *QueryRequested {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClientMessage_QueryRequested); ok {
			return x.QueryRequested
		}
	}
	return nil
}

func (x *ServerToClientMessage) GetQueryResponded() *QueryResponded {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClientMessage_QueryResponded); ok {
			return x.QueryResponded
		}
	}
	return nil
}

func (x *ServerToClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ServerToClientMessage) GetClientRegistrationError() *ClientRegistrationError {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClientMessage_ClientRegistrationError); ok {
			return x.ClientRegistrationError
		}
	}
	return nil
}

func (x *ServerToClientMessage) GetQueryRequestedError() *QueryRequestedError {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClientMessage_QueryRequestedError); ok {
			return x.QueryRequestedError
		}
	}
	return nil
}

func (x *ServerToClientMessage) GetSourceEventRegistered() *SourceEventRegistered {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClientMessage_SourceEventRegistered); ok {
			return x.SourceEventRegistered
		}
	}
	return nil
}

func (x *ServerToClientMessage) GetSourceEvent() *SourceEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClientMessage_SourceEvent); ok {
			return x.SourceEvent
		}
	}
	return nil
}

type isServerToClientMessage_Payload interface {
	isServerToClientMessage_Payload()
}

type ServerToClientMessage_ClientRegistered struct {
	// Confirms that the client registration was accepted.
	ClientRegistered *ClientRegistered `protobuf:"bytes,1,opt,name=client_registered,json=clientRegistered,proto3,oneof"`
}

type ServerToClientMessage_QueryRequested struct {
	// Requests a client to handle a query.
	QueryRequested *QueryRequested `protobuf:"bytes,2,opt,name=query_requested,json=queryRequested,proto3,oneof"`
}

type ServerToClientMessage_QueryResponded struct {
	// Returns a query result to the requesting client.
	QueryResponded *QueryResponded `protobuf:"bytes,3,opt,name=query_responded,json=queryResponded,proto3,oneof"`
}

type ServerToClientMessage_Heartbeat struct {
	// Checks whether the client is still alive.
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type ServerToClientMessage_ClientRegistrationError struct {
	// Indicates that the client could not get registered.
	ClientRegistrationError *ClientRegistrationError `protobuf:"bytes,5,opt,name=client_registration_error,json=clientRegistrationError,proto3,oneof"`
}

type ServerToClientMessage_QueryRequestedError struct {
	// Indicates that there was a problem handling the query requested.
	QueryRequestedError *QueryRequestedError `protobuf:"bytes,6,opt,name=query_requested_error,json=queryRequestedError,proto3,oneof"`
}

type ServerToClientMessage_SourceEventRegistered struct {
	// Indicates that the server has received the event and stored it.
	SourceEventRegistered *SourceEventRegistered `protobuf:"bytes,7,opt,name=source_event_registered,json=sourceEventRegistered,proto3,oneof"`
}

type ServerToClientMessage_SourceEvent struct {
	// Send the event to all the clients.
	SourceEvent *SourceEvent `protobuf:"bytes,8,opt,name=source_event,json=sourceEvent,proto3,oneof"`
}

func (*ServerToClientMessage_ClientRegistered) isServerToClientMessage_Payload() {}

func (*ServerToClientMessage_QueryRequested) isServerToClientMessage_Payload() {}

func (*ServerToClientMessage_QueryResponded) isServerToClientMessage_Payload() {}

func (*ServerToClientMessage_Heartbeat) isServerToClientMessage_Payload() {}

func (*ServerToClientMessage_ClientRegistrationError) isServerToClientMessage_Payload() {}

func (*ServerToClientMessage_QueryRequestedError) isServerToClientMessage_Payload() {}

func (*ServerToClientMessage_SourceEventRegistered) isServerToClientMessage_Payload() {}

func (*ServerToClientMessage_SourceEvent) isServerToClientMessage_Payload() {}

// *
// ClientRegistered confirms that a client has been registered.
type ClientRegistered struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the registered client.
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRegistered) Reset() {
	*x = ClientRegistered{}
	mi := &file_revent_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegistered) ProtoMessage() {}

func (x *ClientRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_revent_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegistered.ProtoReflect.Descriptor instead.
func (*ClientRegistered) Descriptor() ([]byte, []int) {
	return file_revent_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *ClientRegistered) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// *
// ClientRegistrationError indicates that the client could not get registered.
type ClientRegistrationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the client that is not valid.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Reason why the client could not register.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRegistrationError) Reset() {
	*x = ClientRegistrationError{}
	mi := &file_revent_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegistrationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegistrationError) ProtoMessage() {}

func (x *ClientRegistrationError) ProtoReflect() protoreflect.Message {
	mi := &file_revent_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegistrationError.ProtoReflect.Descriptor instead.
func (*ClientRegistrationError) Descriptor() ([]byte, []int) {
	return file_revent_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ClientRegistrationError) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientRegistrationError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_revent_v1_control_proto protoreflect.FileDescriptor

const file_revent_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17revent/v1/control.proto\x12\trevent.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1erevent/v1/query_messages.proto\x1a\x1erevent/v1/event_messages.proto\"\xf7\x02\n" +
	"\x15ClientToServerMessage\x12D\n" +
	"\x0fregister_client\x18\x01 \x01(\v2\x19.revent.v1.RegisterClientH\x00R\x0eregisterClient\x12>\n" +
	"\rquery_request\x18\x02 \x01(\v2\x17.revent.v1.QueryRequestH\x00R\fqueryRequest\x12A\n" +
	"\x0equery_response\x18\x03 \x01(\v2\x18.revent.v1.QueryResponseH\x00R\rqueryResponse\x12T\n" +
	"\x15register_source_event\x18\x04 \x01(\v2\x1e.revent.v1.RegisterSourceEventH\x00R\x13registerSourceEvent\x124\n" +
	"\theartbeat\x18\x05 \x01(\v2\x14.revent.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"^\n" +
	"\x0eRegisterClient\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bclientId\x12*\n" +
	"\x0equery_handlers\x18\x02 \x03(\tB\x03\xe0A\x01R\rqueryHandlers\"\v\n" +
	"\tHeartbeat\"\x81\x05\n" +
	"\x15ServerToClientMessage\x12J\n" +
	"\x11client_registered\x18\x01 \x01(\v2\x1b.revent.v1.ClientRegisteredH\x00R\x10clientRegistered\x12D\n" +
	"\x0fquery_requested\x18\x02 \x01(\v2\x19.revent.v1.QueryRequestedH\x00R\x0equeryRequested\x12D\n" +
	"\x0fquery_responded\x18\x03 \x01(\v2\x19.revent.v1.QueryRespondedH\x00R\x0equeryResponded\x124\n" +
	"\theartbeat\x18\x04 \x01(\v2\x14.revent.v1.HeartbeatH\x00R\theartbeat\x12`\n" +
	"\x19client_registration_error\x18\x05 \x01(\v2\".revent.v1.ClientRegistrationErrorH\x00R\x17clientRegistrationError\x12T\n" +
	"\x15query_requested_error\x18\x06 \x01(\v2\x1e.revent.v1.QueryRequestedErrorH\x00R\x13queryRequestedError\x12Z\n" +
	"\x17source_event_registered\x18\a \x01(\v2 .revent.v1.SourceEventRegisteredH\x00R\x15sourceEventRegistered\x12;\n" +
	"\fsource_event\x18\b \x01(\v2\x16.revent.v1.SourceEventH\x00R\vsourceEventB\t\n" +
	"\apayload\"/\n" +
	"\x10ClientRegistered\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"N\n" +
	"\x17ClientRegistrationError\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2b\n" +
	"\aControl\x12W\n" +
	"\vOpenSession\x12 .revent.v1.ClientToServerMessage\x1a .revent.v1.ServerToClientMessage\"\x00(\x010\x01B\xad\x01\n" +
	"\rcom.revent.v1B\fControlProtoP\x01ZIgithub.com/manuelarte/revent-sdk-go/internal/revent/v1/revent/v1;reventv1\xa2\x02\x03RXX\xaa\x02\tRevent.V1\xca\x02\tRevent\\V1\xe2\x02\x15Revent\\V1\\GPBMetadata\xea\x02\n" +
	"Revent::V1b\x06proto3"

var (
	file_revent_v1_control_proto_rawDescOnce sync.Once
	file_revent_v1_control_proto_rawDescData []byte
)

func file_revent_v1_control_proto_rawDescGZIP() []byte {
	file_revent_v1_control_proto_rawDescOnce.Do(func() {
		file_revent_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_revent_v1_control_proto_rawDesc), len(file_revent_v1_control_proto_rawDesc)))
	})
	return file_revent_v1_control_proto_rawDescData
}

var file_revent_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_revent_v1_control_proto_goTypes = []any{
	(*ClientToServerMessage)(nil),   // 0: revent.v1.ClientToServerMessage
	(*RegisterClient)(nil),          // 1: revent.v1.RegisterClient
	(*Heartbeat)(nil),               // 2: revent.v1.Heartbeat
	(*ServerToClientMessage)(nil),   // 3: revent.v1.ServerToClientMessage
	(*ClientRegistered)(nil),        // 4: revent.v1.ClientRegistered
	(*ClientRegistrationError)(nil), // 5: revent.v1.ClientRegistrationError
	(*QueryRequest)(nil),            // 6: revent.v1.QueryRequest
	(*QueryResponse)(nil),           // 7: revent.v1.QueryResponse
	(*RegisterSourceEvent)(nil),     // 8: revent.v1.RegisterSourceEvent
	(*QueryRequested)(nil),          // 9: revent.v1.QueryRequested
	(*QueryResponded)(nil),          // 10: revent.v1.QueryResponded
	(*QueryRequestedError)(nil),     // 11: revent.v1.QueryRequestedError
	(*SourceEventRegistered)(nil),   // 12: revent.v1.SourceEventRegistered
	(*SourceEvent)(nil),             // 13: revent.v1.SourceEvent
}
var file_revent_v1_control_proto_depIdxs = []int32{
	1,  // 0: revent.v1.ClientToServerMessage.register_client:type_name -> revent.v1.RegisterClient
	6,  // 1: revent.v1.ClientToServerMessage.query_request:type_name -> revent.v1.QueryRequest
	7,  // 2: revent.v1.ClientToServerMessage.query_response:type_name -> revent.v1.QueryResponse
	8,  // 3: revent.v1.ClientToServerMessage.register_source_event:type_name -> revent.v1.RegisterSourceEvent
	2,  // 4: revent.v1.ClientToServerMessage.heartbeat:type_name -> revent.v1.Heartbeat
	4,  // 5: revent.v1.ServerToClientMessage.client_registered:type_name -> revent.v1.ClientRegistered
	9,  // 6: revent.v1.ServerToClientMessage.query_requested:type_name -> revent.v1.QueryRequested
	10, // 7: revent.v1.ServerToClientMessage.query_responded:type_name -> revent.v1.QueryResponded
	2,  // 8: revent.v1.ServerToClientMessage.heartbeat:type_name -> revent.v1.Heartbeat
	5,  // 9: revent.v1.ServerToClientMessage.client_registration_error:type_name -> revent.v1.ClientRegistrationError
	11, // 10: revent.v1.ServerToClientMessage.query_requested_error:type_name -> revent.v1.QueryRequestedError
	12, // 11: revent.v1.ServerToClientMessage.source_event_registered:type_name -> revent.v1.SourceEventRegistered
	13, // 12: revent.v1.ServerToClientMessage.source_event:type_name -> revent.v1.SourceEvent
	0,  // 13: revent.v1.Control.OpenSession:input_type -> revent.v1.ClientToServerMessage
	3,  // 14: revent.v1.Control.OpenSession:output_type -> revent.v1.ServerToClientMessage
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_revent_v1_control_proto_init() }
func file_revent_v1_control_proto_init() {
	if File_revent_v1_control_proto != nil {
		return
	}
	file_revent_v1_query_messages_proto_init()
	file_revent_v1_event_messages_proto_init()
	file_revent_v1_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientToServerMessage_RegisterClient)(nil),
		(*ClientToServerMessage_QueryRequest)(nil),
		(*ClientToServerMessage_QueryResponse)(nil),
		(*ClientToServerMessage_RegisterSourceEvent)(nil),
		(*ClientToServerMessage_Heartbeat)(nil),
	}
	file_revent_v1_control_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerToClientMessage_ClientRegistered)(nil),
		(*ServerToClientMessage_QueryRequested)(nil),
		(*ServerToClientMessage_QueryResponded)(nil),
		(*ServerToClientMessage_Heartbeat)(nil),
		(*ServerToClientMessage_ClientRegistrationError)(nil),
		(*ServerToClientMessage_QueryRequestedError)(nil),
		(*ServerToClientMessage_SourceEventRegistered)(nil),
		(*ServerToClientMessage_SourceEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_revent_v1_control_proto_rawDesc), len(file_revent_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_revent_v1_control_proto_goTypes,
		DependencyIndexes: file_revent_v1_control_proto_depIdxs,
		MessageInfos:      file_revent_v1_control_proto_msgTypes,
	}.Build()
	File_revent_v1_control_proto = out.File
	file_revent_v1_control_proto_goTypes = nil
	file_revent_v1_control_proto_depIdxs = nil
}
