// (-- api-linter: core::0191::proto-package=disabled
//     aip.dev/not-precedent: We need to do this because reasons. --)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: revent/v1/event_messages.proto

package reventv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// RegisterSourceEvent message sent by a client to indicate that an event happened.
type RegisterSourceEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the event.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Unique identifier of the aggregate.
	AggregateId string `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	// Type of the aggregate that generated the event.
	AggregateType string `protobuf:"bytes,3,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	// Event encoded as JSON bytes.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Metadata information of the event.
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSourceEvent) Reset() {
	*x = RegisterSourceEvent{}
	mi := &file_revent_v1_event_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSourceEvent) ProtoMessage() {}

func (x *RegisterSourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_revent_v1_event_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSourceEvent.ProtoReflect.Descriptor instead.
func (*RegisterSourceEvent) Descriptor() ([]byte, []int) {
	return file_revent_v1_event_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSourceEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RegisterSourceEvent) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *RegisterSourceEvent) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *RegisterSourceEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RegisterSourceEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SourceEventRegistered struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the event.
	EventId        string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MonotonicClock uint64 `protobuf:"varint,2,opt,name=monotonic_clock,json=monotonicClock,proto3" json:"monotonic_clock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SourceEventRegistered) Reset() {
	*x = SourceEventRegistered{}
	mi := &file_revent_v1_event_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceEventRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceEventRegistered) ProtoMessage() {}

func (x *SourceEventRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_revent_v1_event_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceEventRegistered.ProtoReflect.Descriptor instead.
func (*SourceEventRegistered) Descriptor() ([]byte, []int) {
	return file_revent_v1_event_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SourceEventRegistered) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SourceEventRegistered) GetMonotonicClock() uint64 {
	if x != nil {
		return x.MonotonicClock
	}
	return 0
}

type SourceEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unique identifier of the event.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// time when the event was stored in the server.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// represents the monotonic clock of the event.
	MonotonicClock uint64 `protobuf:"varint,3,opt,name=monotonic_clock,json=monotonicClock,proto3" json:"monotonic_clock,omitempty"`
	// / unique identifier of the aggregate type.
	AggregateType string `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	// unique identifier of the aggregate instance.
	AggregateId string `protobuf:"bytes,5,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	// the serialized event.
	Payload       *structpb.Struct `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceEvent) Reset() {
	*x = SourceEvent{}
	mi := &file_revent_v1_event_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceEvent) ProtoMessage() {}

func (x *SourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_revent_v1_event_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceEvent.ProtoReflect.Descriptor instead.
func (*SourceEvent) Descriptor() ([]byte, []int) {
	return file_revent_v1_event_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SourceEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SourceEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SourceEvent) GetMonotonicClock() uint64 {
	if x != nil {
		return x.MonotonicClock
	}
	return 0
}

func (x *SourceEvent) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *SourceEvent) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *SourceEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_revent_v1_event_messages_proto protoreflect.FileDescriptor

const file_revent_v1_event_messages_proto_rawDesc = "" +
	"\n" +
	"\x1erevent/v1/event_messages.proto\x12\trevent.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/field_info.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x02\n" +
	"\x13RegisterSourceEvent\x12&\n" +
	"\bevent_id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\aeventId\x12&\n" +
	"\faggregate_id\x18\x02 \x01(\tB\x03\xe0A\x02R\vaggregateId\x12*\n" +
	"\x0eaggregate_type\x18\x03 \x01(\tB\x03\xe0A\x02R\raggregateType\x12\x1d\n" +
	"\apayload\x18\x04 \x01(\fB\x03\xe0A\x02R\apayload\x12M\n" +
	"\bmetadata\x18\x05 \x03(\v2,.revent.v1.RegisterSourceEvent.MetadataEntryB\x03\xe0A\x01R\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x15SourceEventRegistered\x12&\n" +
	"\bevent_id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\aeventId\x12,\n" +
	"\x0fmonotonic_clock\x18\x02 \x01(\x04B\x03\xe0A\x02R\x0emonotonicClock\"\xa4\x02\n" +
	"\vSourceEvent\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x02\xe2\x8c\xcf\xd7\b\x02\b\x01R\x02id\x12>\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\tcreatedAt\x12,\n" +
	"\x0fmonotonic_clock\x18\x03 \x01(\x04B\x03\xe0A\x02R\x0emonotonicClock\x12*\n" +
	"\x0eaggregate_type\x18\x04 \x01(\tB\x03\xe0A\x02R\raggregateType\x12&\n" +
	"\faggregate_id\x18\x05 \x01(\tB\x03\xe0A\x02R\vaggregateId\x126\n" +
	"\apayload\x18\x06 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x02R\apayloadB\xb3\x01\n" +
	"\rcom.revent.v1B\x12EventMessagesProtoP\x01ZIgithub.com/manuelarte/revent-sdk-go/internal/revent/v1/revent/v1;reventv1\xa2\x02\x03RXX\xaa\x02\tRevent.V1\xca\x02\tRevent\\V1\xe2\x02\x15Revent\\V1\\GPBMetadata\xea\x02\n" +
	"Revent::V1b\x06proto3"

var (
	file_revent_v1_event_messages_proto_rawDescOnce sync.Once
	file_revent_v1_event_messages_proto_rawDescData []byte
)

func file_revent_v1_event_messages_proto_rawDescGZIP() []byte {
	file_revent_v1_event_messages_proto_rawDescOnce.Do(func() {
		file_revent_v1_event_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_revent_v1_event_messages_proto_rawDesc), len(file_revent_v1_event_messages_proto_rawDesc)))
	})
	return file_revent_v1_event_messages_proto_rawDescData
}

var file_revent_v1_event_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_revent_v1_event_messages_proto_goTypes = []any{
	(*RegisterSourceEvent)(nil),   // 0: revent.v1.RegisterSourceEvent
	(*SourceEventRegistered)(nil), // 1: revent.v1.SourceEventRegistered
	(*SourceEvent)(nil),           // 2: revent.v1.SourceEvent
	nil,                           // 3: revent.v1.RegisterSourceEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
}
var file_revent_v1_event_messages_proto_depIdxs = []int32{
	3, // 0: revent.v1.RegisterSourceEvent.metadata:type_name -> revent.v1.RegisterSourceEvent.MetadataEntry
	4, // 1: revent.v1.SourceEvent.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: revent.v1.SourceEvent.payload:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_revent_v1_event_messages_proto_init() }
func file_revent_v1_event_messages_proto_init() {
	if File_revent_v1_event_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_revent_v1_event_messages_proto_rawDesc), len(file_revent_v1_event_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_revent_v1_event_messages_proto_goTypes,
		DependencyIndexes: file_revent_v1_event_messages_proto_depIdxs,
		MessageInfos:      file_revent_v1_event_messages_proto_msgTypes,
	}.Build()
	File_revent_v1_event_messages_proto = out.File
	file_revent_v1_event_messages_proto_goTypes = nil
	file_revent_v1_event_messages_proto_depIdxs = nil
}
